use super::{Template, TemplateCategory, TemplateField};
use crate::platform::Platform;

pub fn get_builtin_templates() -> Vec<Template> {
    vec![
        Template {
            id: "ghibli-style".to_string(),
            name: "Ghibli Style Portrait".to_string(),
            category: TemplateCategory::Image,
            platform: Platform::Midjourney,
            description: "Transform any subject into Studio Ghibli anime style".to_string(),
            trending: true,
            fields: vec![TemplateField {
                name: "subject".to_string(),
                label: "Your Subject".to_string(),
                placeholder: "a cat sitting on a windowsill".to_string(),
                required: true,
            }],
            template: "{{subject}}, Studio Ghibli anime style, hand-drawn animation aesthetic, soft pastel colors, detailed background, Hayao Miyazaki inspired, whimsical atmosphere, cel shading, nostalgic mood --ar 3:4 --v 6 --niji 6".to_string(),
        },
        Template {
            id: "action-figure".to_string(),
            name: "Action Figure Box".to_string(),
            category: TemplateCategory::Image,
            platform: Platform::Midjourney,
            description: "Create a toy action figure packaging style image".to_string(),
            trending: true,
            fields: vec![TemplateField {
                name: "subject".to_string(),
                label: "Character/Subject".to_string(),
                placeholder: "a software engineer".to_string(),
                required: true,
            }],
            template: "{{subject}} as a collectible action figure in sealed toy packaging, plastic blister pack, detailed miniature accessories, product photography, studio lighting, realistic plastic texture --ar 3:4 --v 6 --style raw".to_string(),
        },
        Template {
            id: "pixar-character".to_string(),
            name: "Pixar Character".to_string(),
            category: TemplateCategory::Image,
            platform: Platform::Midjourney,
            description: "Transform into a 3D Pixar-style animated character".to_string(),
            trending: true,
            fields: vec![TemplateField {
                name: "subject".to_string(),
                label: "Character Description".to_string(),
                placeholder: "a friendly robot chef".to_string(),
                required: true,
            }],
            template: "{{subject}}, Pixar animation style, 3D rendered character, expressive eyes, colorful, high quality CGI, Disney Pixar aesthetic, detailed textures, warm lighting --ar 1:1 --v 6".to_string(),
        },
        Template {
            id: "90s-yearbook".to_string(),
            name: "90s Yearbook Photo".to_string(),
            category: TemplateCategory::Image,
            platform: Platform::Midjourney,
            description: "Retro 1990s school yearbook portrait style".to_string(),
            trending: true,
            fields: vec![TemplateField {
                name: "subject".to_string(),
                label: "Subject".to_string(),
                placeholder: "a golden retriever".to_string(),
                required: true,
            }],
            template: "{{subject}}, 1990s school yearbook portrait, laser beam background, soft focus, nostalgic, retro studio photography, warm tones, slightly faded, classic school photo pose --ar 3:4 --v 6".to_string(),
        },
        Template {
            id: "oil-painting".to_string(),
            name: "Oil Painting Portrait".to_string(),
            category: TemplateCategory::Image,
            platform: Platform::Generic,
            description: "Classical oil painting style portrait".to_string(),
            trending: false,
            fields: vec![TemplateField {
                name: "subject".to_string(),
                label: "Subject".to_string(),
                placeholder: "a woman in a garden".to_string(),
                required: true,
            }],
            template: "{{subject}}, classical oil painting style, rich color palette, visible brushstrokes, dramatic chiaroscuro lighting, Renaissance inspired composition, museum quality, detailed and textured".to_string(),
        },
        Template {
            id: "cyberpunk-scene".to_string(),
            name: "Cyberpunk Scene".to_string(),
            category: TemplateCategory::Image,
            platform: Platform::Generic,
            description: "Neon-lit futuristic cyberpunk scene".to_string(),
            trending: false,
            fields: vec![TemplateField {
                name: "subject".to_string(),
                label: "Scene Description".to_string(),
                placeholder: "a street market at night".to_string(),
                required: true,
            }],
            template: "{{subject}}, cyberpunk aesthetic, neon lights, rain-slicked streets, holographic advertisements, futuristic technology, moody atmosphere, cinematic lighting, blade runner inspired, 8K quality".to_string(),
        },
        Template {
            id: "code-review".to_string(),
            name: "Code Review Expert".to_string(),
            category: TemplateCategory::Text,
            platform: Platform::Claude,
            description: "Get a thorough code review with actionable feedback".to_string(),
            trending: true,
            fields: vec![TemplateField {
                name: "code".to_string(),
                label: "Your Code".to_string(),
                placeholder: "Paste your code here...".to_string(),
                required: true,
            }],
            template: "Please review the following code thoroughly:\n\n```\n{{code}}\n```\n\nProvide:\n1. **Critical Issues** - Bugs, security vulnerabilities, or logic errors\n2. **Performance** - Inefficiencies or optimization opportunities\n3. **Code Quality** - Naming, structure, readability improvements\n4. **Best Practices** - Industry standard patterns that should be applied\n5. **Testing** - Suggest key test cases\n\nFor each issue, provide the specific line/section and a concrete fix.".to_string(),
        },
        Template {
            id: "technical-explainer".to_string(),
            name: "Technical Explainer".to_string(),
            category: TemplateCategory::Text,
            platform: Platform::Generic,
            description: "Get clear, layered explanations of technical concepts".to_string(),
            trending: false,
            fields: vec![TemplateField {
                name: "topic".to_string(),
                label: "Technical Topic".to_string(),
                placeholder: "Kubernetes pod scheduling".to_string(),
                required: true,
            }],
            template: "Explain {{topic}} at three levels:\n\n1. **ELI5** (1-2 sentences, simple analogy)\n2. **Intermediate** (1 paragraph, key concepts and how they connect)\n3. **Expert** (detailed explanation with technical accuracy, trade-offs, and when to use/avoid)\n\nInclude a practical example for each level.".to_string(),
        },
        Template {
            id: "blog-writer".to_string(),
            name: "Blog Post Writer".to_string(),
            category: TemplateCategory::Text,
            platform: Platform::Generic,
            description: "Generate SEO-optimized blog content".to_string(),
            trending: false,
            fields: vec![TemplateField {
                name: "topic".to_string(),
                label: "Blog Topic".to_string(),
                placeholder: "Getting started with Rust".to_string(),
                required: true,
            }],
            template: "Write a blog post about: {{topic}}\n\nRequirements:\n- **Length**: 1000-1500 words\n- **Tone**: Professional but approachable\n- **Structure**: Hook intro, clear sections with H2 headers, actionable conclusion\n- **SEO**: Include the topic naturally in the first paragraph and headings\n- **Value**: Include at least 3 practical tips or insights the reader can apply immediately\n- **Format**: Markdown with proper headings, code blocks if relevant, and a TL;DR at the top".to_string(),
        },
        Template {
            id: "debug-helper".to_string(),
            name: "Debug Assistant".to_string(),
            category: TemplateCategory::Text,
            platform: Platform::Claude,
            description: "Systematic debugging help with structured analysis".to_string(),
            trending: true,
            fields: vec![TemplateField {
                name: "issue".to_string(),
                label: "Describe the Issue".to_string(),
                placeholder: "API returns 500 error when uploading files larger than 5MB".to_string(),
                required: true,
            }],
            template: "I need help debugging this issue:\n\n**Problem**: {{issue}}\n\nPlease help me with a systematic approach:\n\n1. **Likely Causes** - List the top 3-5 most probable causes, ranked by likelihood\n2. **Diagnostic Steps** - For each cause, what specific check or command can confirm/eliminate it\n3. **Quick Fixes** - Immediate workarounds if applicable\n4. **Root Fix** - The proper solution for each likely cause\n5. **Prevention** - How to prevent this class of issue in the future\n\nStart with the most likely cause and work down.".to_string(),
        },
    ]
}
